version: "2.0"

services:

  postgres_bifrost:
    container_name: postgres_bifrost
    image: postgres:9.6
    environment:
      POSTGRES_DB: bifrost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  bifrost:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/run-standalone-dev.sh
    container_name: bifrost
    image: bifrost
    volumes:
      - .:/code
      - static-content:/static
    ports:
      - "8080:8080"
    depends_on:
      - postgres_bifrost
    environment:
      DJANGO_SETTINGS_MODULE: "bifrost-api.settings.production"
      ALLOWED_HOSTS: "*"
      CORS_ORIGIN_WHITELIST: "*"
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "bifrost"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_bifrost"
      DATABASE_PORT: "5432"
      DEFAULT_OAUTH_DOMAINS: "toladata.com,humanitec.com"
      DOCUMENTATION_URL: "https://humanitec.gitbook.io/frontend-guide/"
      API_URL: "/api/docs"
      JWT_ISSUER: "bifrost"
      JWT_PRIVATE_KEY_RSA_BIFROST: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIBOwIBAAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRBqhqvJu1hKPYn9HYd75c0
        gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQJAe5z5096oyeqGX6J+RGGx
        11yuDJ7J+0N4tthUHSWWUtgkd19NvmTM/mVLmPCzZHgNUT+aWUKsQ84+jhru/NQD
        0QIhAOHOzFmjxjTAR1jspn6YtJBKQB40tvT6WEvm2mKm0aD7AiEAyRPwXyZf3JT+
        M6Ui0Mubs7Qb/E4g1d/kVL+o/XoZC6cCIQC+nKzPtnooKW+Q1yOslgdGDgeV9/XB
        Ulqap+MNh7hJZQIgZNaM+wqhlFtbx8aO2SrioJI4XqVHrjojpaSgOM3cdY0CIQDB
        Q6ckOaDV937acmWuiZhxuG2euNLwNbMldtCV5ADo/g==
        -----END RSA PRIVATE KEY-----
      JWT_PUBLIC_KEY_RSA_BIFROST: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
      RABBIT_HOST: "35.233.76.75"
      RABBIT_PORT: "5672"
      RABBIT_USER: "celery_user"
      RABBIT_PASS: "Y0tGekI2eGUzQlc4"
      RABBIT_VHOST: "celery_vhost"
      RABBIT_WALHALL_QUEUE: "walhall_queue"
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "1090285679254-ep8e9kh2p2juqq8u169fqr5ijfnuaihm.apps.googleusercontent.com"
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "kfy1DGJ3POZYtWMGX0l1yoMi"
      SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS: "gmail.com"
      SOCIAL_AUTH_LOGIN_REDIRECT_URL: "http://dev-v2.tolaactivity.app.tola.io/"
      SOCIAL_AUTH_MICROSOFT_GRAPH_KEY: "63783b55-0c15-4e94-8ceb-4de040fea71d"
      SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL: "https://localhost:8000/complete/microsoft-graph"
      SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET: "w8zgk5dz5JVErCNzc8Jz7EM"
      TOLA_TRACK_SYNC_ENABLED: "False"
      SECRET_KEY: "ek*)b=mtcc7q1cym@oox(lyrz1ncz-(w+(#&u7l-&)7a8wv#_k"

volumes:
  static-content:
