version: "3.1"

services:

  postgres_buildly:
    container_name: postgres_buildly
    image: postgres:9.6
    environment:
      POSTGRES_DB: buildly
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  buildly:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/scripts/run-standalone-dev.sh
    container_name: buildly
    image: buildly
    volumes:
      - .:/code
      - static-content:/static
    ports:
      - "8080:8080"
    depends_on:
      - postgres_buildly
    environment:
      DJANGO_SETTINGS_MODULE: "buildly.settings.production"
      ALLOWED_HOSTS: "*"
      CORS_ORIGIN_WHITELIST: "http://localhost:8000"
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "buildly"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_buildly"
      DATABASE_PORT: "5432"
      DEFAULT_ORG: "Default Organization"
      AUTO_APPROVE_USER: "False"
      JWT_ISSUER: "buildly"
      JWT_PRIVATE_KEY_RSA_BUILDLY: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIBOwIBAAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRBqhqvJu1hKPYn9HYd75c0
        gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQJAe5z5096oyeqGX6J+RGGx
        11yuDJ7J+0N4tthUHSWWUtgkd19NvmTM/mVLmPCzZHgNUT+aWUKsQ84+jhru/NQD
        0QIhAOHOzFmjxjTAR1jspn6YtJBKQB40tvT6WEvm2mKm0aD7AiEAyRPwXyZf3JT+
        M6Ui0Mubs7Qb/E4g1d/kVL+o/XoZC6cCIQC+nKzPtnooKW+Q1yOslgdGDgeV9/XB
        Ulqap+MNh7hJZQIgZNaM+wqhlFtbx8aO2SrioJI4XqVHrjojpaSgOM3cdY0CIQDB
        Q6ckOaDV937acmWuiZhxuG2euNLwNbMldtCV5ADo/g==
        -----END RSA PRIVATE KEY-----
      JWT_PUBLIC_KEY_RSA_BUILDLY: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
      SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URL: "https://localhost:8000/complete/google-oauth2"
      SOCIAL_AUTH_LOGIN_REDIRECT_URL: "http://localhost:8080/"
      SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL: "https://localhost:8000/complete/microsoft-graph"
      ACCESS_TOKEN_EXPIRE_SECONDS: "86400"
      SECRET_KEY: "ek*)b=mtcc7q1cym@oox(lyrz1ncz-(w+(#&u7l-&)7a8wv#_k"
      OAUTH_CLIENT_ID: "wkXLlC9h3k0jxIx7oLllxpFVU89Dxgi7O8FYZyfX"
      OAUTH_CLIENT_SECRET: "KiKRft8MajLabQId7pjSsa3OfvJAXN9NENi0tVRTX3Vbthr6iClEDZZtbyGuD9M8UbKpK2E8R4xJYUolZxg1nVa1iZwhQPi5ionOKdpIs4de2bmUaZ0qWi4MdBmdwDvF"
      USE_PASSWORD_USER_ATTRIBUTE_SIMILARITY_VALIDATOR: "True"
      USE_PASSWORD_MINIMUM_LENGTH_VALIDATOR: "True"
      PASSWORD_MINIMUM_LENGTH: "6"
      USE_PASSWORD_COMMON_VALIDATOR: "True"
      USE_PASSWORD_NUMERIC_VALIDATOR: "True"

      FRONTEND_URL: "http://localhost:3000/"
      SOCIAL_AUTH_GITHUB_REDIRECT_URL: "http://localhost:3000/"
      SOCIAL_AUTH_GITHUB_KEY: "25fc5ab2bdfca0e70c63"
      SOCIAL_AUTH_GITHUB_SECRET: "ff981a6390929445153092d0dbbf4a507c0ecf8b"
      # SOCIAL_AUTH_CLIENT_ID: "vBn4KsOCthm7TWzMH0kVV0dXkUPJEtOQwaLu0eoC"
      # SOCIAL_AUTH_CLIENT_SECRET: "0aYDOHUNAxK4MjbnYOHhfrKx8Ezj3jd7aKq2C7yRDZ6FbAL4SgRFxY8N6GbB6IGyCgpT6pmQ5pEVJmH7mIEUJxyXKbta7ebxULLULjXwnJYGhUgT2hPyCfptkWFhsZVV"

      EMAIL_HOST: "smtp.sendgrid.net"
      EMAIL_HOST_USER: "apikey"
      EMAIL_HOST_PASSWORD: "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"
      EMAIL_PORT: "587"
      EMAIL_USE_TLS: "False"
      EMAIL_SUBJECT_PREFIX: "NO REPLY: Buildly - "
      EMAIL_BACKEND: "SMTP"
      DEFAULT_FROM_EMAIL: "admin@buildly.io"
      RESETPASS_CONFIRM_URL_PATH: "reset-password-confirm/"
      STRIPE_SECRET: ""


volumes:
  static-content:
